-- Seed data for cuisines table
-- Generated from cuisine_cleaned.txt
-- Total: 66 unique cuisines aligned with Yelp categories

INSERT INTO public.cuisines (name, description) VALUES
('Afghan', 'Afghan cuisine'),
('American', 'American cuisine'),
('Argentine', 'Argentine cuisine'),
('Armenian', 'Armenian cuisine'),
('Asian Fusion', 'Asian Fusion cuisine'),
('Bakeries', 'Bakeries and baked goods'),
('BBQ', 'Barbecue'),
('Brazilian', 'Brazilian cuisine'),
('Breakfast & Brunch', 'Breakfast and brunch'),
('Bubble Tea', 'Bubble tea and tea drinks'),
('Burgers', 'Burgers and burger joints'),
('Burmese', 'Burmese cuisine'),
('Cafes', 'Cafes and coffee shops'),
('Cajun/Creole', 'Cajun and Creole cuisine'),
('Caribbean', 'Caribbean cuisine'),
('Caterers', 'Catering services'),
('Cheesesteaks', 'Cheesesteaks'),
('Chicken Wings', 'Chicken wings'),
('Chinese', 'Chinese cuisine'),
('Coffee & Tea', 'Coffee and tea'),
('Colombian', 'Colombian cuisine'),
('Comfort Food', 'Comfort food'),
('Desserts', 'Desserts and sweets'),
('Dim Sum', 'Dim sum'),
('Donuts', 'Donuts and doughnuts'),
('Ethiopian', 'Ethiopian cuisine'),
('Fast Food', 'Fast food'),
('Filipino', 'Filipino cuisine'),
('Food Trucks', 'Food trucks'),
('French', 'French cuisine'),
('Georgian', 'Georgian cuisine'),
('Greek', 'Greek cuisine'),
('Halal', 'Halal food'),
('Hawaiian', 'Hawaiian cuisine'),
('Healthy', 'Healthy food options'),
('Himalayan/Nepalese', 'Himalayan and Nepalese cuisine'),
('Indian', 'Indian cuisine'),
('Indonesian', 'Indonesian cuisine'),
('Iranian', 'Iranian cuisine'),
('Italian', 'Italian cuisine'),
('Japanese', 'Japanese cuisine'),
('Korean', 'Korean cuisine'),
('Laotian', 'Laotian cuisine'),
('Latin American', 'Latin American cuisine'),
('Lebanese', 'Lebanese cuisine'),
('Mediterranean', 'Mediterranean cuisine'),
('Mexican', 'Mexican cuisine'),
('Middle Eastern', 'Middle Eastern cuisine'),
('Noodles', 'Noodle dishes'),
('Pakistani', 'Pakistani cuisine'),
('Pasta', 'Pasta dishes'),
('Persian', 'Persian cuisine'),
('Pizza', 'Pizza'),
('Poke', 'Poke bowls'),
('Ramen', 'Ramen'),
('Salad', 'Salads'),
('Sandwiches', 'Sandwiches'),
('Steakhouses', 'Steakhouses'),
('Sushi Bars', 'Sushi bars'),
('Taiwanese', 'Taiwanese cuisine'),
('Tex-Mex', 'Tex-Mex cuisine'),
('Thai', 'Thai cuisine'),
('Vegan', 'Vegan food'),
('Vegetarian', 'Vegetarian food'),
('Venezuelan', 'Venezuelan cuisine'),
('Vietnamese', 'Vietnamese cuisine'),
('Wraps', 'Wraps and rolled sandwiches')
ON CONFLICT (name) DO NOTHING;

-- Verify insertion
SELECT COUNT(*) as total_cuisines FROM public.cuisines;
