BEGIN;
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('New York', 'NY', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Los Angeles', 'CA', 'US', 'America/Los_Angeles');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Chicago', 'IL', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Houston', 'TX', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Phoenix', 'AZ', 'US', 'America/Phoenix');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Philadelphia', 'PA', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('San Antonio', 'TX', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('San Diego', 'CA', 'US', 'America/Los_Angeles');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Dallas', 'TX', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('San Jose', 'CA', 'US', 'America/Los_Angeles');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Austin', 'TX', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Jacksonville', 'FL', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Fort Worth', 'TX', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Columbus', 'OH', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Charlotte', 'NC', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('San Francisco', 'CA', 'US', 'America/Los_Angeles');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Indianapolis', 'IN', 'US', 'America/Indiana/Indianapolis');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Seattle', 'WA', 'US', 'America/Los_Angeles');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Denver', 'CO', 'US', 'America/Denver');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Washington', 'DC', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Boston', 'MA', 'US', 'America/New_York');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('El Paso', 'TX', 'US', 'America/Denver');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Detroit', 'MI', 'US', 'America/Detroit');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Nashville', 'TN', 'US', 'America/Chicago');
INSERT INTO public.cities (name, state_code, country_code, timezone) VALUES ('Portland', 'OR', 'US', 'America/Los_Angeles');
COMMIT;
