"use client";

import { Bar, BarChart, CartesianGrid, XAxis } from "recharts";

import {
    type ChartConfig,
    ChartContainer,
    ChartTooltip,
    ChartTooltipContent,
} from "@/components/ui/chart";

export const title = "A bar chart";

const chartData = [
    { month: "January", desktop: 186 },
    { month: "February", desktop: 305 },
    { month: "March", desktop: 237 },
    { month: "April", desktop: 73 },
    { month: "May", desktop: 209 },
    { month: "June", desktop: 214 },
];

const chartConfig = {
    desktop: {
        label: "Desktop",
        color: "hsl(var(--chart-1))", // Ensure HSL wrapper if needed, or just var(--chart-1) if defined as color
    },
} satisfies ChartConfig;

// Note: The original code used "var(--chart-1)" directly in color, but shadcn charts usually expect HSL or a valid color string.
// If "var(--chart-1)" resolves to "12 34% 56%", it needs "hsl(...)". 
// However, standard shadcn themes usually define --chart-1 as a full HSL value without the function, so "hsl(var(--chart-1))" is safer, 
// OR if it's a hex/color, it's fine.
// Let's stick to the original code but be aware. 
// Wait, the original code had `color: "var(--chart-1)"`.
// And `<Bar fill="var(--color-desktop)" ... />`
// The config key is "desktop", so `var(--color-desktop)` is automatically generated by ChartContainer from the config color.

const ChartBarDefault = () => (
    <div className="w-full max-w-xl rounded-md border bg-background p-4">
        <ChartContainer config={chartConfig}>
            <BarChart accessibilityLayer data={chartData}>
                <CartesianGrid vertical={false} />
                <XAxis
                    axisLine={false}
                    dataKey="month"
                    tickFormatter={(value) => value.slice(0, 3)}
                    tickLine={false}
                    tickMargin={10}
                />
                <ChartTooltip
                    content={<ChartTooltipContent hideLabel />}
                    cursor={false}
                />
                <Bar dataKey="desktop" fill="var(--color-desktop)" radius={8} />
            </BarChart>
        </ChartContainer>
    </div>
);

export default ChartBarDefault;
